services:
  mssqldb:
    container_name: mssqldb
    hostname: mssqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-C",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "${MSSQL_PASSWORD}",
          "-Q",
          "SELECT 1",
        ]
      interval: 1s
      timeout: 30s
      retries: 30
      start_period: 5s

  restapi:
    container_name: restapi
    build: ./
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:7165
      - ASPNETCORE_URLS=http://+:5067
    ports:
      - 5067:5067
      - 7165:7165
    depends_on:
      mssqldb:
        condition: service_healthy

volumes:
  mssql_data:
